Adiciona tradução capitulo 1.1.4
syncship/compondo-programas pull request #13
Opened 2021-02-01 23:41 UTC by ratsclub

2021-02-02 23:18 UTC, d4sein commented on src/ch01-01-04-first-example.md
> +Para uma introdução adequada do Python, nós iniciaremos com uma exemplo que utiliza diversas funcionalidades da linguagem. Na próxima seção, nós começaremos do zero e trabalharemos peça a peça da lin
Corrigir **linha 12** `...nós começaremos do zero e trabalharemos peça a peça da linguagem.` -> `nós começaremos do zero e aprenderemos sobre a linguagem etapa por etapa.`

2021-02-02 23:22 UTC, d4sein requested changes
Revisão parou na linha 12.

2021-02-02 23:22 UTC, d4sein commented on src/ch01-01-04-first-example.md
> +Para uma introdução adequada do Python, nós iniciaremos com uma exemplo que utiliza diversas funcionalidades da linguagem. Na próxima seção, nós começaremos do zero e trabalharemos peça a peça da lin
Corrigir **linha 12** `...nós começaremos do zero e trabalharemos peça a peça da linguagem.` -> `nós começaremos do zero e aprenderemos sobre a linguagem etapa por etapa.`

2021-02-13 23:53 UTC, d4sein commented on src/ch01-01-04-first-example.md
> +Para uma introdução adequada do Python, nós iniciaremos com uma exemplo que utiliza diversas funcionalidades da linguagem. Na próxima seção, nós começaremos do zero e aprenderemos sobre a linguagem e
Corrigir **linha 12** `...nós iniciaremos com uma exemplo...` => `...nós iniciaremos com um exemplo...`

2021-02-13 23:55 UTC, d4sein commented on src/ch01-01-04-first-example.md
> +Python possui suporte embutido para uma vasta gama de atividades comuns na programação, como manipulação de texto, exibição de gráficos e comunicção pela Internet. A linha de código Python
Corrigir **linha 14** `...exibição de gráficos e comunicção pela Internet.` => `...exibição de gráficos e comunicação pela Internet.`

2021-02-14 00:04 UTC, d4sein commented on src/ch01-01-04-first-example.md
> +**Funções**. Funções encapsulam lógicas que manipulam dados. `urlopen` é uma função. Um endereço *Web* é um pedaço de dado, e os textos de Shakespeare é outro. O processo onde o primeiro dado se tran
Alterar **linha 37** pra contextualizar melhor "piece of data", `Um endereço *Web* é um pedaço de dado...` => `Um endereço *Web* é um conjunto de dados...`

2021-02-14 00:07 UTC, d4sein commented on src/ch01-01-04-first-example.md
> +associam o nome `words` ao *set* (conjunto) de palavras únicas que aparecem nas peças de Shakespeare, todas as 33.721 palavras. A corrente the comandos `read` (ler), `decode` (decodificar), e `split`
Corrigir **linha 45**, onde "(it) associates" se refere a "Another assignment statement", no singular.  `associam o nome...` => `associa o nome...`

2021-02-14 00:12 UTC, d4sein commented on src/ch01-01-04-first-example.md
> +**Objetos**. Um *set* é um tipo de objeto, um que suporta operações como interseções e associação. Um obejto agrupa os dados e a lógica que os manipula, de uma forma que gerencia a complexidade de am
Corrigir **linha 47** `Um obejto agrupa...` => `Um objeto agrupa`

2021-02-14 00:15 UTC, d4sein commented on src/ch01-01-04-first-example.md
> +é uma expressão composta que avalia o conjunto de todas as palavras *Shakesperianas* que continuam uma palavra se escritas ao contrário. A expressão enigmática `w[::-1]` enumera cada letra em uma pal
Corrigir **linha 54**, "evaluates to" se refere ao resultado da expressão. `é uma expressão composta que avalia o conjunto...` => `é uma expressão composta que resulta no conjunto`.

2021-02-14 00:17 UTC, d4sein commented on src/ch01-01-04-first-example.md
> +**Interpretadores**. Avaliar expressões compostas requer um procedimento preciso que interpreta o código de uma forma previsível. Um programa que implementa esse procedimento, avaliando expressões co
Corrigir **linha 56**, `Avaliar expressões compostas requer um procedimento preciso...` => `A resolução de expressões compostas requer um procedimento preciso...`

2021-02-14 00:21 UTC, ratsclub commented on src/ch01-01-04-first-example.md
> +Para uma introdução adequada do Python, nós iniciaremos com uma exemplo que utiliza diversas funcionalidades da linguagem. Na próxima seção, nós começaremos do zero e aprenderemos sobre a linguagem e
Fixed: 3a0d0d3d64e33159a06091392d025befe754761b

2021-02-14 00:21 UTC, d4sein requested changes
Review completa, merge pode ser feito após as correções.

2021-02-14 00:27 UTC, ratsclub commented on src/ch01-01-04-first-example.md
> +Python possui suporte embutido para uma vasta gama de atividades comuns na programação, como manipulação de texto, exibição de gráficos e comunicção pela Internet. A linha de código Python
https://github.com/syncship/compondo-programas/pull/13/commits/b388e884b65db051db7b075d965d25404776a072

2021-02-14 00:28 UTC, ratsclub commented on src/ch01-01-04-first-example.md
> +**Funções**. Funções encapsulam lógicas que manipulam dados. `urlopen` é uma função. Um endereço *Web* é um pedaço de dado, e os textos de Shakespeare é outro. O processo onde o primeiro dado se tran
https://github.com/syncship/compondo-programas/pull/13/commits/c1f60699bf49228c3cf6b4b3c3fec91b669f62d4

2021-02-14 00:28 UTC, ratsclub commented on src/ch01-01-04-first-example.md
> +associam o nome `words` ao *set* (conjunto) de palavras únicas que aparecem nas peças de Shakespeare, todas as 33.721 palavras. A corrente the comandos `read` (ler), `decode` (decodificar), e `split`
https://github.com/syncship/compondo-programas/pull/13/commits/a56c126641e68c203fc9a91a810121663c7e4d21

2021-02-14 00:28 UTC, ratsclub commented on src/ch01-01-04-first-example.md
> +**Objetos**. Um *set* é um tipo de objeto, um que suporta operações como interseções e associação. Um obejto agrupa os dados e a lógica que os manipula, de uma forma que gerencia a complexidade de am
https://github.com/syncship/compondo-programas/pull/13/commits/730d1b666ccbb672be8ff3dbdfc3666699fe18c9

2021-02-14 00:28 UTC, ratsclub commented on src/ch01-01-04-first-example.md
> +é uma expressão composta que avalia o conjunto de todas as palavras *Shakesperianas* que continuam uma palavra se escritas ao contrário. A expressão enigmática `w[::-1]` enumera cada letra em uma pal
https://github.com/syncship/compondo-programas/pull/13/commits/4e2bd02d365093816410d4da654b95be9fecaba4

2021-02-14 00:28 UTC, ratsclub commented on src/ch01-01-04-first-example.md
> +**Interpretadores**. Avaliar expressões compostas requer um procedimento preciso que interpreta o código de uma forma previsível. Um programa que implementa esse procedimento, avaliando expressões co
https://github.com/syncship/compondo-programas/pull/13/commits/2010c0ba6625fac6560ee30e335759a953ab0063

2021-02-14 00:31 UTC, merged