Adiciona tradução capitulo 1.1.5
syncship/compondo-programas pull request #14
Opened 2021-02-02 01:48 UTC by ratsclub

2021-02-02 22:13 UTC, d4sein submitted a review, later dismissed

2021-02-14 22:41 UTC, distromari commented on src/ch01-01-05-errors.md
> +Python está esperando por seu comando. Você é incentivado à experimentar com a linguagem, mesmo que você ainda não saiba toda sua estrutura e vocabulário. Entretanto, esteja preparado para erros. Emb
`eles são rígidos na mesma proporção` => `eles também são extremamente rígidos`

2021-02-14 22:53 UTC, distromari commented on src/ch01-01-05-errors.md
> +4. **Consulte outras pessoas**: Você não está sozinho! Se você não entende uma mensagem de erro, pergunte a um amigo, instrutor, ou motor de pesquisa. Se você isolou um erro, mas não consegue descobr
No final, frase faltando: ´Muitos conhecimentos valiosos de programação são compartilhados no processo de resolução de problemas em grupo.´
Pode alterá-la da melhor maneira.

2021-02-14 22:56 UTC, ratsclub commented on src/ch01-01-05-errors.md
> +Python está esperando por seu comando. Você é incentivado à experimentar com a linguagem, mesmo que você ainda não saiba toda sua estrutura e vocabulário. Entretanto, esteja preparado para erros. Emb
Mas aí fica meio repetitivo o *extremamente*, não acha?

2021-02-14 22:57 UTC, distromari requested changes
Correção de tradução e adicionar frase que estava faltando.

2021-02-14 22:58 UTC, distromari commented on src/ch01-01-05-errors.md
> +Python está esperando por seu comando. Você é incentivado à experimentar com a linguagem, mesmo que você ainda não saiba toda sua estrutura e vocabulário. Entretanto, esteja preparado para erros. Emb
> Mas aí fica meio repetitivo o _extremamente_, não acha?

Realmente.

2021-02-17 00:26 UTC, d4sein commented on src/ch01-01-05-errors.md
> +Python está esperando por seu comando. Você é incentivado à experimentar com a linguagem, mesmo que você ainda não saiba toda sua estrutura e vocabulário. Entretanto, esteja preparado para erros. Emb
Remover a crase `..incentivado à experimentar..` => `..incentivado a experimentar..`, "a" é preposição, e experimentar não tem artigo.

2021-02-17 00:34 UTC, d4sein commented on src/ch01-01-05-errors.md
> +> Computadores são muito potentes, analisando volumes de dados bem rápido. Computadores podem realizar bilhões de operações por segundo, desde que estas operações sejam simples.
Corrigir `..desde que estas operações sejam simples.` => `..onde cada operação é bem simples.`. Acredito que o contexto em que ele fala isso tem a ver com a complexidade última de um computador operando com machine-readable code.

2021-02-17 00:38 UTC, d4sein commented on src/ch01-01-05-errors.md
> +A rigidez dos computadores se tornará imediatamente aparente enquanto você experimenta com o interpretador Python: até mesmo o menor erro de digitação ou mudança na formatação do código causarão erro
Corrigir `..imediatamente aparente enquanto você experimenta com o interpretador Python` => `..imediatamente aparente à medida em que você experimenta com o interpretador Python`

2021-02-17 00:39 UTC, d4sein commented on src/ch01-01-05-errors.md
> +Aprender a interpretar os erros e diagnosticar as causas de erros inesperados é chamado de *debugging*.
Faltando traduzir `Some guiding principles of debugging are:`

2021-02-17 00:40 UTC, d4sein commented on src/ch01-01-05-errors.md
> +1. **Teste incrementalmente**: Todo programa bem-escrito é composto de componentes pequenos e modulares que podem ser testados individualmente. Teste tudo que você escrever o mais rápido possível par
Remover hífen `bem-escrito` => `bem escrito`.

2021-02-17 00:44 UTC, d4sein commented on src/ch01-01-05-errors.md
> +3. **Verifique suas suposições**: Interpretadores levam suas instruções ao pé da letra - sem mais nem menos. Sua saída é inesperada quando o comportamento de um código não condiz com o que o programa
Corrigir `..sem mais nem menos.` => `..nem mais, nem menos.`, aqui ele fala de algo preciso, não algo que não tem explicação 🤪

2021-02-17 00:47 UTC, d4sein requested changes
Favor fazer as CORREÇÕES

2021-02-18 00:23 UTC, ratsclub commented on src/ch01-01-05-errors.md
> +1. **Teste incrementalmente**: Todo programa bem-escrito é composto de componentes pequenos e modulares que podem ser testados individualmente. Teste tudo que você escrever o mais rápido possível par
Maldito acordo ortográfico

2021-02-18 01:21 UTC, merged